name: Sync GitHub Teams

on:
  push:
    paths:
      - 'teams/**/*.json'
  workflow_dispatch:

jobs:
  sync-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./.github/actions/org-management
        run: npm ci

      - name: Build action
        working-directory: ./.github/actions/org-management
        run: npm run build

      - name: Sync GitHub Team
        uses: ./.github/actions/org-management
        with:
          github-token: ${{ secrets.ORG_MANAGEMENT_TOKEN }}
          config-path: './teams'
          org-name: 'OleksSyde'
