name: Sync GitHub Teams

on:
  push:
    paths:
      - 'teams/**/*.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync GitHub Team
        uses: ./.github/actions/org-management
        with:
          github-token: ${{ secrets.ORG_MANAGEMENT_TOKEN }}
          config-path: './teams'
          org-name: 'OleksSyde'
